<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP_Dtos_Layer\DominLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Accounts\" />
    <Folder Include="Features\InventoryMovements\" />
    <Folder Include="Features\SalesTransactions\" />
    <Folder Include="Mapper\Accounts\" />
    <Folder Include="Mapper\Inventory Movements\" />
    <Folder Include="Mapper\Sales Transactions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" Version="10.0.2" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

</Project>
